version: '3'
services:

  l_server1:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - ../p_src:/usr/share/nginx/html/p
    networks:
      - network_LB_back_1

  l_server2:
    image: nginx
    ports:
      - "8082:80"
    volumes:
      - ../m_src:/usr/share/nginx/html/m
    networks:
      - network_LB_back_2

  lb:
    build: .
    ports:
      - "8080:80"
    networks:
      - default
      - network_LB_back_1
      - network_LB_back_2

networks:
  network_LB_front:
    external: true
  network_LB_back_1:
    external: true
  network_LB_back_2:
    external: true

  # web:
  #   image: nginx
  #   ports:
  #   - "7000:80"
  #   volumes:
  #   - ./mysite.template:/etc/nginx/conf.d/mysite.template
  #   environment:
  #   - NGINX_HOST=foobar.com
  #   - NGINX_PORT=80
  #   command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"