version: '3'
services:

  l_server1:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - ../p_src:/usr/share/nginx/html/p
    networks:
      - network_LB_back_1

  l_server2:
    image: nginx
    ports:
      - "8082:80"
    volumes:
      - ../m_src:/usr/share/nginx/html/m
    networks:
      - network_LB_back_2

  web_python:
    container_name: web_python
    build:
      context: .
      dockerfile: DockerfilePython
    ports:
      - "8083:80"
    hostname: web_python
    deploy:
      replicas: 1
    networks:
      - network_LB_back_3

  web_python_flask:
    container_name: web_python_flask
    build:
      context: .
      dockerfile: DockerfilePython2
    ports:
      - "8084:80"
    hostname: web_python_flask
    deploy:
      replicas: 1
    networks:
      - network_LB_back_4


  lb:
    container_name: lb
    build: .
    ports:
      - "8888:80"
    networks:
      - default
      - network_LB_back_1
      - network_LB_back_2
      - network_LB_back_3
      - network_LB_back_4
      # - network_LB_back_5

  lbout:
    build:
      context: .
      dockerfile: DockerfileNginx
    ports:
      - "8080:80"
      - "7070:443"
    networks:
      - default
      # - network_LB_back_4
      # - network_LB_back_5

networks:
  network_LB_front:
    external: true
  network_LB_back_1:
    external: true
  network_LB_back_2:
    external: true
  network_LB_back_3:
    external: true
  network_LB_back_4:
    external: true
  # network_LB_back_5:
  #   external: true